name: starinvest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  country_flags: ^4.1.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.5
  intl: ^0.19.0

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          style: normal
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          style: normal
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          style: normal
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: normal
